export const KUCZYNSKI_ECONOMICS_QUESTIONS = [
  "What ratios make up Altman's Z-score?",
  "Why does Altman's formula give EBIT divided by assets its largest coefficient?",
  "What does market value of equity divided by total liabilities measure?",
  "What Z-score does the writing treat as the minimum for financial health?",
  "How do Amazon, BlackBerry, and Sears illustrate the meaning of Z-scores?",
  "What five factors does Moody's use to rate software companies?",
  "Why does Moody's weight leverage and coverage more heavily than profitability?",
  "How do market-share, product diversity, end-market diversity, and geographic diversity shape a business profile?",
  "Why can both excessive specialization and excessive diversification harm a company?",
  "What does a company's financial policy reveal about its risk-taking and debt repayment?",
  "Why does Moody's give scale a lower weight than leverage and coverage?",
  "Why is long-term profitability more informative than a brief burst of profit?",
  "Why are discount rates assumptions rather than known facts in financial analysis?",
  "What standard and non-standard accounting adjustments does Moody's consider?",
  "What does Microsoft's operating cash flow from 2016 through 2018 indicate about its products and services?",
  "How does Microsoft's 2018 net-income decline complicate an otherwise positive financial picture?",
  "What do Microsoft's current and quick ratios suggest about liquidity and cash use?",
  "Why did inadequate accounting processes threaten RutgersCo with lost revenue and sanctions?",
  "How did RutgersCo's firing of accounting staff affect competence and morale?",
  "How did Leeson's dummy account and false paper trail conceal Barings' unauthorized trades?",
  "Why should trading and settlement duties be separated in a bank?",
  "What warning signs did Barings management ignore before the bank failed?",
  "Why does Zara's focused use of customer analytics outperform Wearable Wishes' generic concept?",
  "How do accurate demand forecasts affect Zara's inventory, discounts, employment, and market share?",
  "How does Zara's control of its supply chain benefit retailers and customers?",
  "Who does IKEA target, and why does furniture assembly fit that market?",
  "How did IKEA adapt its products and stores to American and Chinese customers?",
  "How does IKEA's store design turn shopping into a total experience?",
  "Why does a deliberate marketing strategy improve a firm's profitability?",
  "How does Facebook convert virtual identity, business pages, mobile use, and Instagram into advertising revenue?",
  "Why does the writing call drug prohibition economically expensive?",
  "How could legal drug sales improve quality control, age restrictions, and public safety?",
  "Why might legalization remove the incentive for pushers to create captive customers?",
  "What economic benefits does the writing attribute to California's legalization of marijuana?",
  "Why would Kant and Ross reject coercive equalization of wealth?",
  "In what ways does the writing argue that participation in a free market can still be unfree?",
  "Why does the writing favor a carbon tax over relying solely on standing environmental regulations?",
  "How can carbon taxes encourage efficiency while regulations may protect incumbent firms?",
  "Why does the writing defend minimum wages as a support for worker health and future entrepreneurship?",
  "Why does the writing argue that excessive minimum-wage increases can reduce employment and investment?",
  "What two conditions does the writing identify as jointly necessary for Indian states' economic growth?",
  "Why does knowledge, rather than inherited property, drive accumulation in a market economy?",
  "Why does the writing attribute American energy inefficiency to a culture of conspicuous consumption?",
  "Why does the writing expect Ethio Telecom's privatization to attract investment and accelerate growth?",
  "How could privatizing Ethiopia's national airline improve investment confidence and economic activity?",
  "What are hard power, positive soft power, and negative soft power?",
  "How does the writing classify China's Belt and Road Initiative as multiple kinds of soft power?",
  "Why did American politics stabilize into a two-party system despite the absence of parties at the founding?",
  "How does the writing characterize the enduring economic and social division between the two major parties?",
  "Why does the writing identify falling petroleum prices as the proximate cause of the Soviet collapse?",
  "Why did the Soviet Union's lack of a legitimate free market make a return to communism impractical?",
  "How does the writing describe Russia's constitutional system differently from its practical system?",
  "Why does the writing regard strong centralized leadership as potentially effective in Russia?",
  "How did Russia's geography contribute to isolation, weak agriculture, and centralized rule?",
  "What advantage and disadvantage of semi-presidential government does the writing identify for France?",
  "Why does the writing portray Plato's ideal state as dependent on ignorance and official falsehoods?",
  "What economic considerations made the United States receptive to entering World War I?",
  "Why does the writing distinguish the economic reasons for entering World War I from Wilson's actual motive?",
  "How did the Treaty of Versailles damage Germany's economy and contribute to later remilitarization?",
  "What problem is knowledge management intended to solve inside an organization?",
  "How did Smith-Jones-Brown lose a potential client through poor knowledge management?",
  "Why does the writing present OneClass as an example of poor knowledge management?",
  "Why are knowledge-management problems easier to prevent when an organization is designed than to repair later?",
  "Why does selling definite results support knowledge management better than selling vaguely defined services?",
  "Why does the writing link effective internal communication to performance-dependent employment and pay?",
  "How does direct client hiring make employee contribution and pricing more financially transparent?",
  "Why does the writing argue that education should be digitized whenever possible?",
  "Why does DMO use independent, anonymous, examination-based accreditations instead of instructor grades?",
  "How would DMO use lighter science programs to move humanities-oriented students toward STEM?",
  "Why must DMO instructors not function as gatekeepers?",
  "Why should DMO payments go directly from students to instructors?",
  "Why does the writing say universities can remain financially healthy despite low retention and graduation rates?",
  "Why does the writing claim that colleges sell degrees more than instruction?",
  "Why might students prefer less demanding instruction even though some professions require genuine knowledge?",
  "When does the writing regard dropping out of college as a rational way to cut losses?",
] as const;