export const KUCZYNSKI_APPLIED_QUESTIONS = [
  "What do retention and graduation rates measure, and why do they diverge?",
  "Why can a university with very low retention remain financially stable?",
  "Why does enrollment matter more than retention to a university's finances?",
  "Why do colleges sell degrees rather than instruction?",
  "Why can a degree make someone employable even when it adds little knowledge?",
  "Why would making a college genuinely more instructional alienate its customers?",
  "Why does a university's optimal instruction tend to be merely good enough?",
  "When is dropping out a rational hedge rather than a tragedy?",
  "Why can knowledge management not repair universities' retention problem?",
  "What is the difference between reactive and proactive knowledge management?",
  "Why did Lehman Brothers' reactive knowledge management fail?",
  "Why should education be digitized whenever possible?",
  "What does DMO sell instead of prestige?",
  "Why must DMO's accreditations be examination-based and independently graded?",
  "Why does DMO permit students to test out?",
  "Why should DMO students pay instructors directly?",
  "Why does DMO reject permanent employment and tenure?",
  "How does DMO turn instruction into proof of competence?",
  "Why does DMO avoid excluding students who need instruction?",
  "What is the inverted payment pyramid, and why does it matter?",
  "Why does the free market generate inequalities that it cannot itself resolve?",
  "Why does Kuczynski assign government responsibility for reducing those disparities?",
  "How can progressive taxation preserve capitalism while reducing inequality?",
  "What is the economic case for legalizing drugs?",
  "Why does drug prohibition impose costs without a corresponding security gain?",
  "Why might prohibition increase drug use?",
  "What is the difference between colonialism and imperialism?",
  "How did European imperialism stimulate European economic development?",
  "How did Russian geography impede political development?",
  "What caused the Soviet Union's collapse in Kuczynski's account?",
  "Why did Russia move from state planning toward a market economy after the Soviet collapse?",
  "How does Kuczynski characterize Russia's constitutional system in practice?",
  "Why might semi-autocratic governance fit Russia's conditions?",
  "Why does Kuczynski question the assumption that democracy always functions better?",
  "How does the Electoral College make the American presidency only indirectly democratic?",
  "Why is the Senate only qualifiedly democratic in Kuczynski's constitutional analysis?",
  "Why does Kuczynski distinguish legitimate reasons for war from actual causes?",
  "What are positive and negative soft power?",
  "How can negative soft power be deliberate or inadvertent?",
  "Why can free-market participation feel unfree despite economic freedom?",
  "How does Tocqueville's individualism divide classical liberals from Rousseau and Marx?",
  "Why does Kuczynski argue that pollution regulation need not restrict a free market?",
  "What makes a literary or narrated work beautiful under the content-bioavailability account?",
  "Why must style and narration align with content?",
  "Why does Kuczynski reject aesthetic relativism in music?",
  "What psychological and social function does Kuczynski assign to musical relativism?",
  "How does “Scared to Be Lonely” balance repetition and variation?",
  "Which musical elements make that song memorable?",
  "How does the song distribute melody, harmony, and instrumentation?",
  "Why does Kuczynski see medieval music as relevant to modern music?",
  "How does the austerity of “Caro Mea” shape its character?",
  "How do “Ordo Virtutum” and “A Chantar” differ in emotional and instrumental qualities?",
  "What are the two ways knowledge must be organized?",
  "Why must people share knowledge to achieve their goals?",
  "What is collective knowledge?",
  "Why can poor internal communication make institutional problems intractable?",
  "Why must knowledge management treat knowledge as an asset rather than merely an asset-precursor?",
  "Why does Kuczynski say knowledge management requires performance-dependent pay and financial transparency?",
  "What does the fraud triangle explain, and what cases does it exclude?",
  "What three conditions enable high-level workplace fraud?",
  "How can clear fund-handling rules reduce fraud?",
  "Why do supervision and checks and balances reduce fraud opportunities?",
  "Why can an employer's own dishonesty help employees rationalize fraud?",
  "What five traits define a reliable employee?",
  "Why is self-discipline the root of the other work traits?",
  "How should rational decision-making proceed from problem definition to option selection?",
  "Why should options be compared by total costs rather than headline salary?",
  "When is accepting a job without requisite training morally permissible?",
  "Why should a candidate decline a complex, high-stakes job without confidence in rapid learning?",
  "What distinguishes actual intelligence from possession of intelligence-derived cognitive structures?",
  "Why does unexercised intellect atrophy?",
  "How can permanent academic positions preserve the reputation of diminished intellects?",
  "What causes writer's block according to Kuczynski?",
  "Why can questions and dialogue unlock a writer's material?",
  "Why does written language make rationalism and large-scale social organization possible?",
] as const;