export const KUCZYNSKI_ADDITIONAL_200_QUESTIONS = [
"Is reference a word-object relation at all, or a relation between propositions and the inferences they license?",
"Does Kripke's causal theory of names collapse into descriptivism at the baptism point?",
"Do indexicals have semantic characters, or only pragmatic recovery rules?",
"Is metaphor a use of language or a use of belief-states?",
"Can truth-conditional semantics handle sentences whose function is to alter inferential dispositions rather than to describe?",
"Is compositionality a constraint on meaning or only on learnability?",
"Is vagueness a property of concepts or of the relation between concepts and applications?",
"Are Grice's maxims norms of conversation or consequences of rational inference under uncertainty?",
"Does the semantics/pragmatics distinction survive cases where literal content is recoverable only pragmatically?",
"Does analyticity survive Quine once theoretical definition is separated from conceptual containment?",
"What is the difference between saying something and meaning it?",
"Can a sentence have a meaning no one has ever grasped?",
"Is translation indeterminate in any sense that matters to practice?",
"Are proper names rigid because of how they refer or because of how we argue with them?",
"What would a semantics look like that took inference rather than truth as primitive?",
"Is \"meaning\" a single concept or a family of unrelated ones?",
"Do natural languages have a logical form, or only logical regimentations?",
"Is ambiguity a defect in language or a design feature?",
"Can there be a private language in any sense Wittgenstein actually ruled out?",
"Is speaker meaning prior to sentence meaning, or the reverse?",
"Can functionalism distinguish a system that has a mental state from one that models one?",
"Are qualia intrinsic properties or relational properties of discriminative capacities?",
"Is introspection perception or inference?",
"Is the unity of consciousness a datum or a presupposition of how we individuate experiences?",
"Can intentionality be naturalized without individuating the naturalizing relation intentionally?",
"Is mental causation problematic only if causal relations must hold between events under descriptions?",
"Does the extended-mind thesis confuse the vehicle of a process with its subject?",
"Is belief a propositional attitude or a disposition to use a proposition as a premise?",
"Is self-deception paradoxical, or does the paradox depend on identifying the deceiving and deceived subjects?",
"Do unconscious mental states have the same epistemic status as unobservable physical entities?",
"What would count as evidence that a machine understands something?",
"Is there anything it is like to be a system that reports there is?",
"Is the hard problem a problem about consciousness or about explanation?",
"Can a thought be false without being about anything?",
"Does thinking require a language?",
"Is emotion a species of judgment, a species of perception, or neither?",
"What individuates a desire — its object, its causal role, or its satisfaction conditions?",
"Is akrasia possible, or is every case a misdescription of the agent's actual preference?",
"Could two people have qualitatively identical experiences and disagree about them without either being wrong?",
"Is personal identity a metaphysical fact or a bookkeeping convention?",
"Do Gettier cases refute JTB, or show that \"justification\" is used equivocally across the conditions?",
"Is knowledge a mental state or a status conferred by a community?",
"Does epistemic closure fail because inference is a causal process with a nonzero error rate?",
"Can Bayesian epistemology represent conceptual innovation, which alters the partition rather than the distribution?",
"Is testimony a distinct source of knowledge or compressed inference about speaker reliability?",
"Is the problem of induction about justification or about the individuation of properties?",
"Is external-world skepticism statable without presupposing what it denies?",
"Why does justification come in degrees when knowledge does not?",
"Does peer disagreement give a reason to revise when it traces to differing priors rather than evidence?",
"Is understanding a species of knowledge, or a capacity that can outrun knowledge entirely?",
"What is the epistemic value of an explanation that is false but predictively perfect?",
"Can you be justified in believing something you cannot articulate?",
"Is there such a thing as knowing how without knowing that?",
"Is evidence a relation between propositions or between a person and the world?",
"Should credences ever be extreme?",
"How much of what we call \"expertise\" is calibrated judgment and how much is credential signaling?",
"Is intellectual humility a virtue or a strategy?",
"When is it rational to refuse to update?",
"Can a body of beliefs be individually justified and jointly irrational?",
"Is skepticism about testimony self-undermining?",
"Are mathematical objects positions in structures, and are those positions reducible to inferential roles?",
"Does every argument from Gödel to anti-mechanism equivocate on \"sees that\"?",
"Is set theory the foundation of mathematics or one codification among several?",
"Does the applicability of mathematics to nature need explaining, given that nature is individuated mathematically?",
"Is logical consequence truth-preservation in all models or warrant-preservation in all extensions of commitments?",
"Do paraconsistent logics tolerate contradictions or merely redescribe them?",
"Is the axiom of choice a mathematical assumption or a decision about what counts as a specification?",
"Is mathematical infinity a syntactic device with no ontological commitment?",
"Is probability a measure over worlds or over degrees of inferential commitment?",
"Does formalization ever clarify an argument whose validity is not already secure?",
"What makes a proof explanatory rather than merely valid?",
"Is mathematical intuition evidence or heuristic?",
"Could mathematics have gone differently?",
"Are there mathematical truths no proof could establish, and would that matter?",
"Is arithmetic analytic?",
"Is the continuum hypothesis a question with an answer?",
"What is the relationship between computability and knowability?",
"Does the success of applied statistics depend on any coherent interpretation of probability?",
"Is a definition ever a discovery?",
"Why do mathematicians agree so much more than philosophers?",
"What does analytic philosophy currently reward, and does it overlap with what it claims to value?",
"Are dissertation gatekeeping decisions tracking quality or tracking conformity?",
"Is peer review a filter for correctness or for familiarity?",
"What happens to a field when its publication volume exceeds any individual's reading capacity?",
"Has professionalization made philosophy better or only more legible?",
"Is ghostwriting in academia a symptom of a credentialing problem or an authorship problem?",
"What would academic philosophy look like with no tenure and no journals?",
"Can an outsider still contribute to a technical philosophical literature?",
"Why do so many philosophical disputes persist without resolution, and is that a defect?",
"Is the \"publish or perish\" norm responsible for the decline in philosophical ambition, or is something else?",
"Should philosophy be taught to undergraduates at all, and if so, why?",
"Does the seminar format select for verbal fluency over insight?",
"What is lost when philosophy is written for referees rather than readers?",
"Is there a defensible standard of philosophical rigor independent of formal notation?",
"Has the rise of the \"research program\" displaced the philosophical problem as the unit of work?",
"Who were the genuinely first-rate philosophers you encountered personally, and what distinguished them?",
"Is the history of philosophy a philosophical method or a separate discipline?",
"Should philosophers read outside philosophy, and does the profession make that possible?",
"Does the profession have any mechanism for recognizing work it is not already prepared to recognize?",
"What would you change first about how philosophy is produced?",
"Are chain-of-thought gains gains in search rather than in inference?",
"Does benchmark saturation reflect capability or benchmark construction bias?",
"When does retrieval augmentation degrade accuracy rather than improve it?",
"Can gradient attribution tell us anything about attention-routed architectures?",
"Do language models have concepts, or only distributions over uses?",
"Is there a principled difference between a model that understands and a model that predicts what an understander would say?",
"What would a real test of machine comprehension look like, as opposed to a benchmark?",
"Can a model be creative if creativity is novelty of constraint rather than novelty of content?",
"Is \"hallucination\" a failure mode or the normal operation of the mechanism under-constrained?",
"Does scaling change what a model does in kind, or only in degree?",
"What philosophical questions have become empirically tractable because of language models?",
"Should AI systems be evaluated on outputs or on the reliability of the process generating them?",
"Is alignment a technical problem, a political problem, or a conceptual one?",
"Can a system have beliefs without having interests?",
"What does it mean for an AI tutor to assess understanding rather than performance?",
"Will AI raise or lower the value of a written credential?",
"Is prompt engineering a skill, a stopgap, or a symptom?",
"What tasks are language models currently overrated at, and which are they underrated at?",
"Does AI-assisted writing change what authorship means, and should it?",
"What would you build if compute were free?",
"Does lecture outperform active learning for material with high prerequisite density?",
"Was assessment in higher education already measuring compliance rather than competence before AI?",
"Does spaced repetition's advantage survive for material that is used rather than recalled?",
"Is credential inflation driven by employer screening costs rather than student demand?",
"Can understanding be assessed without assessing recall?",
"What is the smallest unit of genuine intellectual progress a course can produce?",
"Should a course be organized around problems or around results?",
"Is there any defensible reason to grade?",
"What does a good exam question look like, and why are they so rare?",
"Can a self-taught person reach the frontier of a technical field, and under what conditions?",
"Is the textbook a dead form?",
"What should a philosophy course teach someone who will never take another one?",
"How do you teach someone to recognize a bad argument they agree with?",
"Does difficulty have pedagogical value independent of content?",
"What is the role of memorization in an era of instant retrieval?",
"Should students be taught to write before they are taught to read closely, or the reverse?",
"Is one-on-one tutoring's advantage attention, feedback latency, or something else?",
"Can curricula be personalized without being fragmented?",
"What does it cost a student to be taught something false but simple first?",
"What would you teach that no one currently teaches?",
"Is leveraged-ETF decay a cost of leverage or a cost of rebalancing frequency?",
"Have index inclusion effects inverted since the growth of passive flows?",
"Does forward guidance lose efficacy through lost credibility or through information saturation?",
"Are minimum-wage employment effects mediated almost entirely by labor-market concentration?",
"Is the equity risk premium an artifact of survivorship among continuously tradable markets?",
"Do options markets systematically misprice tails in capital-expenditure-cyclical sectors?",
"Is mean reversion a property of prices or of the attention of participants?",
"Can a solo trader have a durable edge, and what is its source if so?",
"Is risk a property of positions or of position sizing?",
"What distinguishes a strategy from a rationalized pattern in noise?",
"Are markets informationally efficient in any sense that constrains individual behavior?",
"Is diversification a substitute for understanding or a complement to it?",
"What does it mean to be \"right\" about a trade that loses money?",
"How should one weight backtests against reasoning about mechanism?",
"Is economic forecasting a science, an art, or a genre?",
"Are behavioral biases departures from rationality or adaptations to different statistics?",
"What is the correct discount rate for one's own future preferences?",
"Is it rational to act on a probability you cannot defend numerically?",
"Does money have a marginal utility curve, or several incommensurable ones?",
"What would a genuinely decision-theoretic education consist of?",
"Is tonal function a statistical expectation structure rather than a theoretical postulate?",
"Are counterpoint rules compression heuristics for tracking independent voices?",
"Has streaming distribution made album-length coherence a cost rather than a value?",
"Is canon formation driven by teachability rather than evaluative consensus?",
"Is musical understanding inference about implied continuations?",
"Why does dissonance treatment vary historically while consonance judgments do not?",
"Can a piece of music be wrong?",
"Is musical expression a property of the work or of the performance?",
"Does notation constrain composition, and how much?",
"Is atonality a system or the absence of one?",
"Why does a cappella writing expose compositional weakness that orchestration conceals?",
"Is aesthetic value a property of works or of transactions between works and competent audiences?",
"Is the intentional fallacy a fallacy?",
"Is artistic originality novelty of content or novelty of constraint?",
"Why is aesthetic disagreement more tractable than moral disagreement?",
"Does knowing how a work was made change what it is?",
"Can an artwork be great and boring?",
"Is craft a precondition of art or an alternative to it?",
"What makes a melody memorable, and is that the same as what makes it good?",
"Should composers write for listeners who do not yet exist?",
"What is the single view you hold that you expect to be vindicated last?",
"Which of your published positions have you since abandoned, and why?",
"What is the most overrated argument in twentieth-century philosophy?",
"What is the most underrated?",
"How do you decide what to work on?",
"What does your writing process actually look like?",
"How do you know when an argument is finished?",
"Which thinkers changed your mind, and about what?",
"What do you think you are wrong about right now?",
"Is productivity at your scale a matter of method or of temperament?",
"What is the relationship between your philosophical work and your music?",
"Why write under pen names?",
"What has building software taught you that philosophy did not?",
"What would you say to a graduate student whose advisor has blocked their project?",
"Is there such a thing as intellectual courage, or only indifference to cost?",
"What is the best argument against a view you hold strongly?",
"What do you owe your readers?",
"What work of yours do you most want read in fifty years?",
"What question should someone have asked you that no one does?",
"What would you do differently if you were starting over?",
] as const;