export const KUCZYNSKI_PSYCHOLOGY_QUESTIONS = [
  "Why does experience alter how one is rather than who one is?",
  "What biological limits constrain a person's ability to change himself?",
  "Why does empiricizing psychology not amount to making it scientific?",
  "Why is unconscious mental activity necessary to explain conscious activity?",
  "How does Kuczynski define intelligence?",
  "Why are values not the same as desires?",
  "Why does valuing anything require valuing truth?",
  "How does subpersonal processing relate minds to selves?",
  "Why do beliefs remain operative when they are not conscious?",
  "What is the difference between having a mental attitude and knowing one has it?",
  "Why are emotions enduring structures rather than conscious episodes?",
  "Why are judgment-producing processes not directly voluntary?",
  "Why can group psychology be more basic than individual psychology?",
  "Why cannot individualistic psychology adequately explain conformity?",
  "Why can collectives display intelligence that exceeds the intelligence of their members?",
  "Why does innate cognitive structure make language learning possible?",
  "Why can sensory data alone not explain language acquisition?",
  "Why can physiology support training but not teaching?",
  "Why does Kuczynski deny that alcoholism has a purely medical cure?",
  "How is alcoholism an internal division between drinking and living?",
  "Why can the alcoholic not reliably stop after taking the first drink?",
  "Why does willpower fail to control the alcoholic's drinking?",
  "What psychological function does admitting powerlessness serve in AA?",
  "Why does AA's higher power function as an ego-ideal?",
  "Why must the alcoholic project his values to become aware of them?",
  "Why can AA work for atheists and agnostics?",
  "Why are amends necessary to sustain recovery?",
  "Why must recovery involve action rather than intellectual acceptance?",
  "Why does helping other alcoholics protect against relapse?",
  "What does recovery mean when alcoholism is not cured?",
  "How does surrender realign conduct with the recovering person's values?",
  "Why does action restrain the ego more effectively than inaction?",
  "How does alcoholism function as a flight from reality?",
  "Why can recovering alcoholics call themselves insane while appearing sane?",
  "Why is the alcoholic's leap of faith not literally a surrender to an external power?",
  "How does religious sentiment unify a divided mind?",
  "Why do religious conversion and mind-cure both relax the conscious-unconscious boundary?",
  "When is optimism genuinely self-fulfilling?",
  "Why is self-deception coherent despite its apparent paradox?",
  "What distinguishes repression₁ from repression₂?",
  "How does repression₁ avoid forming unwanted knowledge?",
  "What is the essential mechanism of repression₂?",
  "Why must a belief be a source of intrapsychic conflict to be repressed₂?",
  "Why is suppressing a painful memory different from repression₂?",
  "Why do repressions often outlive the circumstances that created them?",
  "How do gaps created by repression generate further rationalizations?",
  "Why are rationalizations attempts to make the immoral seem moral?",
  "How can rationalization sustain sociopathization?",
  "Why can a person not directly choose what to believe?",
  "How can a person nevertheless make a belief psychologically inert?",
  "Why does the breakdown of repression₁ produce anxiety?",
  "Why are unusually high standards of proof applied to personal beliefs?",
  "How can a repressed belief return as a symptom?",
  "How can a repressed desire disguise itself as an acceptable desire?",
  "Why is the denial of repression itself an instance of repression?",
  "Why does Kuczynski say brain science is parasitic on psychological knowledge?",
  "What distinguishes ego-syntonic from ego-dystonic mental illness?",
  "Why is OCD a neurosis rather than a psychosis?",
  "How does psychosis differ structurally from neurosis?",
  "Why does neurosis involve fleeing one's emotions?",
  "Why does psychosis involve fleeing external reality?",
  "How does borderline personality disorder's splitting differ from repression?",
  "Why does borderline oscillation not by itself amount to lying?",
  "How does a psychopath differ from a sociopath?",
  "Why does Kuczynski treat psychopathy as phoniness rather than criminality?",
  "Why can a criminal have meaningful attachments while a psychopath cannot?",
  "Why does the sociopath imitate morality?",
  "Why do people resist evolutionary kinship with other animals?",
  "Why can the loss of something motivate a person to deprive others of it?",
  "Why is compulsive work a form of avoidance?",
  "How does stuttering reflect competing currents of thought?",
  "When does a psychological condition count as pathological?",
  "How does a person's attachment history shape later personality?",
  "Why does a secure therapeutic relationship matter more than insight alone?",
  "Why do mentally ill people often form relationships that validate their symptoms?",
] as const;