export const KUCZYNSKI_PHILOSOPHY_QUESTIONS = [
  "What three components make up a formal language?",
  "Why must the grammar of a language be recursively defined?",
  "Why is a finite, non-recursive expression-class not a genuine language?",
  "What does a language's meaning-function assign to its sentences?",
  "How can two sentences have the same truth-conditions but different meanings?",
  "In what sense are natural languages formal languages?",
  "Why does natural language's structural richness make its rules difficult to state?",
  "Why does a sentence's logical form amount to its meaning?",
  "Why is a perfectly formal language as incoherent as a square circle?",
  "How does the semantic rule for a proper name determine truth-conditions?",
  "Why is a sentence-token's meaning not simply the proposition it encodes?",
  "Why does assertoric force belong to an expression rather than to a proposition?",
  "Why can no language state all of its own semantic rules?",
  "How can syntax conceal the logical form of a sentence?",
  "How does causal transmission explain the reference of a proper name?",
  "What is formal truth?",
  "Why are negation, conjunction, and disjunction statement-functions?",
  "Why is “because” non-truth-functional?",
  "Why does recursion matter to a logical system?",
  "Why is formal truth relative to a recursive definition?",
  "How does analytic truth differ from formal truth?",
  "What did Gödel show about recursively characterizing all arithmetical truths?",
  "Why are logical consequences of conventions not themselves conventions?",
  "How can rules of inference be understood as conditional propositions?",
  "Why does the negation of “someone is tall” differ from “someone is not tall”?",
  "What does it mean to say that all functions are statement-functions?",
  "Why does logic study formal truth rather than merely valid argument forms?",
  "What is an axiomatic system, and what does its consistency require?",
  "Why does an arithmetic truth need not be formally true?",
  "How does mathematics identify structural invariants?",
  "What is knowledge knowledge of, and why is it not knowledge of objects?",
  "Why are propositions neither linguistic expressions nor beliefs?",
  "What makes a proposition true on the property-set account?",
  "Why is justified true belief insufficient for knowledge?",
  "What makes a physical process information-transmissive?",
  "How do analytic and empirical knowledge differ?",
  "Why is no knowledge strictly observation-based?",
  "Why do observations disclose instances rather than properties themselves?",
  "Why are negative truths not known by observation alone?",
  "Why are disjunctive truths known through non-disjunctive grounds?",
  "In what sense are all empirical beliefs inferential?",
  "Why does knowledge require conceptual articulation of observation?",
  "What are the two epistemic roles of sense-perception?",
  "How does a theory differ from an inference based on one causal mechanism?",
  "Why does the broken-clock case fail to yield knowledge?",
  "Why does the non-skeptical model of perception explain more than hallucination from nowhere?",
  "Why is continuity a better basis for causal knowledge than correlation?",
  "Why is the future expected through continuity rather than resemblance alone?",
  "Why does skepticism become less coherent when it denies persistence?",
  "Why does meaningful predication commit us to properties?",
  "Why are properties not identical with the sets of their instances?",
  "Why are propositions not spatiotemporal facts?",
  "How does instantiatedness explain the truth of a proposition?",
  "Why can a false proposition exist?",
  "Why does spatial occupancy entail causal power?",
  "Why is persistence itself a causal relation?",
  "How does continuity distinguish causation from accidental correlation?",
  "What is the difference between causal efficacy and causal relevance?",
  "How does a causal theory explain rather than merely report regularities?",
  "Why can existence not be proved from logic or from properties alone?",
  "Why does content-externalism threaten the causal existence of mental content?",
  "Why is syntax insufficient to constitute thought?",
  "Why does Kuczynski reject the idea of a language of thought?",
  "Why must representational content be causally involved in a thought-process?",
  "Why does reliable succession between brain-states not by itself constitute reasoning?",
  "Why are beliefs, desires, and intentions genuine mental states rather than behavioral dispositions?",
  "Why is consciousness not identical with information processing?",
  "What distinguishes a mind from a self?",
  "Why do values consolidate agency and selfhood?",
  "Why is free action compatible with determinism?",
  "Why are values, rather than higher-order desires, the basis of freedom?",
  "What distinguishes a person from a merely goal-directed non-person?",
  "How can repression preserve a conflict without making both sides conscious?",
  "Why does rationalization corrupt direct access to one's values?",
  "Why does a psychopath's lack of values limit moral motivation?",
] as const;